## 'StepLR' training
python3 main.py --submode 'vanilla' --modelname 'ENet' --lr_update 'StepLR' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
python3 main.py --submode 'vanilla' --modelname 'ENet_slim0.75' --lr_update 'StepLR' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
python3 main.py --submode 'vanilla' --modelname 'ENet_slim0.5' --lr_update 'StepLR' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
python3 main.py --submode 'vanilla' --modelname 'ENet_slim0.25' --lr_update 'StepLR' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
python3 main.py --submode 'vanilla' --modelname 'ENet_2enc0.5_3enc0.5' --lr_update 'StepLR' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
python3 main.py --submode 'vanilla' --modelname 'ENet_2enc0.5' --lr_update 'StepLR' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
python3 main.py --submode 'vanilla' --modelname 'ENet_3enc0' --lr_update 'StepLR' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
python3 main.py --submode 'vanilla' --modelname 'ENet_3enc0_channel0.75' --lr_update 'StepLR' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
python3 main.py --submode 'vanilla' --modelname 'ENet_3enc0_channel0.6' --lr_update 'StepLR' --dataset 'Cityscapes' --dataset_dir './Cityscapes'

## 'ReduceLROnPlateau' training
python3 main.py --submode 'vanilla' --modelname 'ENet' --lr_update 'ReduceLROnPlateau' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
python3 main.py --submode 'vanilla' --modelname 'ENet_slim0.75' --lr_update 'ReduceLROnPlateau' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
python3 main.py --submode 'vanilla' --modelname 'ENet_slim0.5' --lr_update 'ReduceLROnPlateau' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
python3 main.py --submode 'vanilla' --modelname 'ENet_slim0.25' --lr_update 'ReduceLROnPlateau' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
python3 main.py --submode 'vanilla' --modelname 'ENet_2enc0.5_3enc0.5' --lr_update 'ReduceLROnPlateau' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
python3 main.py --submode 'vanilla' --modelname 'ENet_2enc0.5' --lr_update 'ReduceLROnPlateau' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
python3 main.py --submode 'vanilla' --modelname 'ENet_3enc0' --lr_update 'ReduceLROnPlateau' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
python3 main.py --submode 'vanilla' --modelname 'ENet_3enc0_channel0.75' --lr_update 'ReduceLROnPlateau' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
python3 main.py --submode 'vanilla' --modelname 'ENet_3enc0_channel0.6' --lr_update 'ReduceLROnPlateau' --dataset 'Cityscapes' --dataset_dir './Cityscapes'
